automation updates

diff --git a/benchmark/write-blog b/benchmark/write-blog
--- a/benchmark/write-blog
+++ b/benchmark/write-blog
@@ -1,13 +1,15 @@
 #! /bin/bash
 
-usage="Usage: $0 <summary-file> <blog-file>"
+usage="Usage: $0 <summary-file> [summary-file2] <blog-file>"
 
-if [ "$#" -ne 2 ]; then
+if [ "$#" -lt 2 ]; then
   echo $usage
   exit 1
 fi
-summary_file=$1
-blog_file=$2
+
+summaries=($@)
+blog_file=${summaries[-1]}
+unset summaries[-1]
 
 api_url=https://api.anthropic.com/v1/messages
 api_key=$ANTHROPIC_API_KEY
@@ -19,14 +21,26 @@ model_id=claude-3-5-sonnet-20241022
 anthropic_version=2023-06-01
 
 system_prompt=$(jq -R -s '{"text": .}' benchmark/claude-prompt.md | jq .text)
-summary=$(jq @json < $summary_file)
+summary="[]"
+for summary_file in "${summaries[@]}"; do
+  if [ ! -f "$summary_file" ]; then
+    echo "Error: Summary file not found: $summary_file" >&2
+    exit 1
+  fi
 
-api_body=$(cat <<EOF
+  summary=$(jq --argjson file "$(cat "$summary_file")" '. + [$file]' <<<"$summary")
+done
+
+# Now we want to stringify it, pretty-printed
+summary=$(echo $summary | jq @json)
+
+api_body=$(
+  cat <<EOF
 {
   "model": "$model_id",
   "system": $system_prompt,
-  "max_tokens": 1024,
-  "temperature": 0,
+  "max_tokens": 2048,
+  "temperature": 0.1,
   "messages": [
     {
       "role": "user",
@@ -45,5 +59,12 @@ response=$(
     -d "$api_body" \
     $api_url
 )
+
+# If there is no .content, .content[0] and .content[0].text field, then the API call failed
+if [ -z "$(echo $response | jq -r .content[0].text)" ]; then
+  echo "Error: API call failed" >&2
+  echo $response | jq . >&2
+  exit 1
+fi
 
 echo $response | jq -r .content[0].text > $blog_file
